version: "3.7"
services:

  rabbitmq:
    container_name: rabbitmq
    build:
      context: .
      dockerfile: rabbitmq/Dockerfile
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      local_app_network:
        aliases:
          - rabbitmq

  database:
    container_name: database
    build:
      context: .
      dockerfile: database/Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      local_app_network:
        aliases:
          - database
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

  message-service:
    depends_on:
      - user-service
      - database
      - vote-service
    container_name: message-service
    build:
      context: .
      dockerfile: services/message_service/Dockerfile
    ports:
      - 5002:5000
    environment:
      PYTHONDONTWRITEBYTECODE: ${PYTHONDONTWRITEBYTECODE}
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}
      PYTHONPATH: ${PYTHONPATH}
      ENV: ${ENV}
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:5000/ping || exit 1",
          "CMD-SHELL",
          "curl -f http://localhost:5000/vote_service_health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      local_app_network:
        aliases:
          - message-board.message-service

  auth-service:
    depends_on:
      - user-service
    container_name: auth-service
    build:
      context: .
      dockerfile: services/authentication_service/Dockerfile
    ports:
      - 5005:5000
    environment:
      PYTHONDONTWRITEBYTECODE: ${PYTHONDONTWRITEBYTECODE}
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}
      PYTHONPATH: ${PYTHONPATH}
      ENV: ${ENV}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      local_app_network:
        aliases:
          - message-board.auth-service

  user-service:
    depends_on:
      - database
    container_name: user-service
    build:
      context: .
      dockerfile: services/user_service/Dockerfile
    ports:
      - 5001:5000
    environment:
      PYTHONDONTWRITEBYTECODE: ${PYTHONDONTWRITEBYTECODE}
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}
      PYTHONPATH: ${PYTHONPATH}
      ENV: ${ENV}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      local_app_network:
        aliases:
          - message-board.user-service

  vote-service:
    container_name: vote-service
    build:
      context: .
      dockerfile: services/vote_service/Dockerfile
    ports:
      - 5003:5000
    environment:
      PYTHONDONTWRITEBYTECODE: ${PYTHONDONTWRITEBYTECODE}
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}
      PYTHONPATH: ${PYTHONPATH}
      ENV: ${ENV}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      local_app_network:
        aliases:
          - message-board.vote-service

  api-gateway:
    depends_on:
      - user-service
      - message-service
    container_name: message-board-app
    build:
      context: .
      dockerfile: services/api_gateway/Dockerfile
    ports:
      - 5004:5000
    environment:
      PYTHONDONTWRITEBYTECODE: ${PYTHONDONTWRITEBYTECODE}
      PYTHONUNBUFFERED: ${PYTHONUNBUFFERED}
      PYTHONPATH: ${PYTHONPATH}
      ENV: ${ENV}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      local_app_network:
        aliases:
          - message-board.app

  site:
    container_name: site-app
    build:
      context: .
      dockerfile: services/site/Dockerfile
    ports:
      - 8080:80
    restart: always
    healthcheck:
      test: ["CMD", 'curl', "-f", "http://localhost:80"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      local_app_network:
        aliases:
          - message-board.site

networks:
  local_app_network:
    external: false
